name: CI
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    matrix:
      os: [ ubuntu-latest, macOS-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: Setup workspace
        run: dotnet tool restore
      - name: Build package
        run: dotnet build src
