name: Publish
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install and use custom npm version
        run: npm i -g npm@7
      - name: Setup workspace
        run: npm install
      - name: Build site
        run: npm run docs:build
      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs_deploy
